import assert from 'node:assert/strict';
import test from 'node:test';
import { CollisionWorld, SceneStateManager } from '../src/index.js';
function buildWorld(): { manager: SceneStateManager; world: CollisionWorld } { const manager = new SceneStateManager(); const world = new CollisionWorld(() => manager.getAllObjects(), { floorY: 0 }); return { manager, world }; }
test('CollisionWorld blocks movement into a wall but allows moving away from it', () => { const { manager, world } = buildWorld(); manager.registerObject({ uuid: '20000000-0000-4000-a000-000000000001', assetType: 'cube', transform: { position: { x: 0, y: 1, z: 0 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 2, y: 2, z: 2 } }, metadata: { name: 'Wall', collider: true } }); const blocked = world.movePlayer({ x: 2, y: 1.7, z: 0 }, { x: -1, y: 0, z: 0 }); assert.equal(blocked.blockedX, true); assert.equal(blocked.position.x, 1.35); const away = world.movePlayer({ x: 2, y: 1.7, z: 0 }, { x: 1, y: 0, z: 0 }); assert.equal(away.blockedX, false); assert.equal(away.position.x, 3); });
test('CollisionWorld resolves corner collision stably on X and Z', () => { const { manager, world } = buildWorld(); manager.registerObject({ uuid: '20000000-0000-4000-a000-000000000002', assetType: 'cube', transform: { position: { x: 0, y: 1, z: 0 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 2, y: 2, z: 2 } }, metadata: { name: 'Corner Block', collider: true } }); const result = world.movePlayer({ x: 2, y: 1.7, z: 2 }, { x: -1, y: 0, z: -1 }); assert.ok(result.blockedX || result.blockedZ); assert.ok(result.position.x >= 1); assert.ok(result.position.z >= 1.35); });
test('CollisionWorld enforces boundary collision and player radius', () => { const { manager, world } = buildWorld(); manager.registerObject({ uuid: '20000000-0000-4000-a000-000000000003', assetType: 'cube', transform: { position: { x: 0, y: 1, z: -5 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 10, y: 2, z: 1 } }, metadata: { name: 'North Boundary', collider: true, mapBoundary: true } }); const wide = world.movePlayer({ x: 0, y: 1.7, z: -3.8 }, { x: 0, y: 0, z: -1 }, 0.5); assert.equal(wide.blockedZ, true); assert.equal(wide.position.z, -4); });
test('CollisionWorld handles ground collision and landing on object tops', () => { const { manager, world } = buildWorld(); manager.registerObject({ uuid: '20000000-0000-4000-a000-000000000004', assetType: 'cube', transform: { position: { x: 0, y: 0.5, z: 0 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 2, y: 1, z: 2 } }, metadata: { name: 'Platform', collider: true } }); const floor = world.movePlayer({ x: 5, y: 3, z: 0 }, { x: 0, y: -5, z: 0 }); assert.equal(floor.grounded, true); assert.equal(floor.position.y, 1.7); const platform = world.movePlayer({ x: 0, y: 3, z: 0 }, { x: 0, y: -5, z: 0 }); assert.equal(platform.grounded, true); assert.equal(platform.position.y, 2.7); });
test('CollisionWorld uses conservative rotated-object bounds for supported solids', () => { const { manager, world } = buildWorld(); manager.registerObject({ uuid: '20000000-0000-4000-a000-000000000005', assetType: 'cube', transform: { position: { x: 0, y: 1, z: 0 }, rotation: { x: 0, y: 45, z: 0 }, scale: { x: 2, y: 2, z: 4 } }, metadata: { name: 'Rotated Crate', collider: true } }); const result = world.movePlayer({ x: 3, y: 1.7, z: 0 }, { x: -2, y: 0, z: 0 }); assert.equal(result.blockedX, true); });
