import assert from 'node:assert/strict';
import test from 'node:test';
import * as THREE from 'three';
import { CollisionWorld, PlayerController, SceneStateManager } from '../src/index.js';
function createWorld(): CollisionWorld { const manager = new SceneStateManager(); return new CollisionWorld(() => manager.getAllObjects(), { floorY: 0 }); }
test('PlayerController moves forward and backward', () => { const controller = new PlayerController(createWorld(), { initialPosition: { x: 0, y: 1.7, z: 0 }, yaw: 0 }); controller.update(1, { forward: true }); const forward = controller.getPosition(); assert.ok(forward.z < -5.9); controller.update(1, { backward: true }); const back = controller.getPosition(); assert.ok(back.z > forward.z); });
test('PlayerController strafes left and right', () => { const controller = new PlayerController(createWorld(), { initialPosition: { x: 0, y: 1.7, z: 0 }, yaw: 0 }); controller.update(1, { right: true }); const right = controller.getPosition(); assert.ok(right.x > 5.9); controller.update(1, { left: true }); const left = controller.getPosition(); assert.ok(left.x < right.x); });
test('PlayerController sprint is faster than walking', () => { const walk = new PlayerController(createWorld(), { initialPosition: { x: 0, y: 1.7, z: 0 }, yaw: 0 }); const sprint = new PlayerController(createWorld(), { initialPosition: { x: 0, y: 1.7, z: 0 }, yaw: 0 }); walk.update(1, { forward: true, sprint: false }); sprint.update(1, { forward: true, sprint: true }); assert.ok(Math.abs(sprint.getPosition().z) > Math.abs(walk.getPosition().z)); });
test('PlayerController jump, gravity, and grounded state behave correctly', () => { const controller = new PlayerController(createWorld(), { initialPosition: { x: 0, y: 1.7, z: 0 } }); assert.equal(controller.isGrounded(), true); assert.equal(controller.requestJump(), true); controller.update(0.1); assert.ok(controller.getPosition().y > 1.7); assert.equal(controller.isGrounded(), false); assert.ok(controller.getVerticalVelocity() > 0); for (let i = 0; i < 30; i += 1) controller.update(0.1); assert.equal(controller.isGrounded(), true); assert.equal(controller.getPosition().y, 1.7); });
test('PlayerController updates attached camera and supports camera switching', () => { const camera = new THREE.PerspectiveCamera(70, 1, 0.1, 100); const controller = new PlayerController(createWorld(), { camera, initialPosition: { x: 1, y: 1.7, z: 2 }, yaw: Math.PI }); assert.equal(controller.getCameraMode(), 'first_person'); assert.equal(camera.position.x, 1); assert.equal(camera.position.y, 1.7); assert.equal(camera.position.z, 2); controller.toggleCameraMode(); assert.equal(controller.getCameraMode(), 'third_person'); assert.notEqual(camera.position.z, 2); controller.setCameraMode('first_person'); assert.equal(controller.getCameraMode(), 'first_person'); assert.equal(camera.position.z, 2); });
